### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by Rohitha-pudu**
shifted to the branch landing-page-frontend-ui

### CODE REVIEW

**Review by Witty-Wizard — CHANGES_REQUESTED** [review]
- [x] When I click on view, the new page loads but its contents do not load, I have to reload the page in order for those to load.
- [x] Move the Button component to the src directory
- [x] when hovering over the button make the text black

**Comment by Rohitha-pudu** [comment]
> * [ ]  When I click on view, the new page loads but its contents do not load, I have to reload the page in order for those to load.
its working for me

**Comment by Witty-Wizard** [comment]
> > * [ ]   When I click on view, the new page loads but its contents do not load, I have to reload the page in order for those to load.
>    its working for me
Please share video

**Comment by Rohitha-pudu** [comment]
> > > * [ ]    When I click on view, the new page loads but its contents do not load, I have to reload the page in order for those to load.
> > >   its working for me
> > >   Please share video
ohk .yeah the page is displaying only after the refresh ,but i dont know why its happening like that!

**Comment by Rohitha-pudu** [comment]
> * [ ]  When I click on view, the new page loads but its contents do not load, I have to reload the page in order for those to load.
> 
>     * [ ]  Move the Button component to the src directory
> 
>     * [ ]  when hovering over the button make the text black

done with 2 and 3.but i dont understand the issue 1, why it is happening

**Comment by Witty-Wizard** [comment]
> > * [ ]  When I click on view, the new page loads but its contents do not load, I have to reload the page in order for those to load.
> 
> > 
> 
> >     * [ ]  Move the Button component to the src directory
> 
> > 
> 
> >     * [ ]  when hovering over the button make the text black
> 
> 
> 
> done with 2 and 3.but i dont understand the issue 1, why it is happening

Check the console log there is some error when you first load the page

**Comment by Rohitha-pudu** [comment]
> > > * [ ]   When I click on view, the new page loads but its contents do not load, I have to reload the page in order for those to load.
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * [ ]  Move the Button component to the src directory
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * [ ]  when hovering over the button make the text black
> > > ```
> > 
> > 
> > done with 2 and 3.but i dont understand the issue 1, why it is happening
> 
> Check the console log there is some error when you first load the page

Successfully resolved,you can check now @Witty-Wizard

**Review by Witty-Wizard — APPROVED** [review]
@Rohitha-pudu, I am merging this PR, before that can you please explain the bug and how you solved it so that other people can look into it, if they want to learn.

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu, I am merging this PR, before that can you please explain the bug and how you solved it so that other people can look into it, if they want to learn.

I implemented startTransition to navigate to navigate('/station'),React provides a function called startTransition that lets you tell React that a state update, or a sequence of state updates, can wait.
  const Station = () => {
        // Wrap the state update with startTransition
        startTransition(() => {
            navigate('/Station');
        });
    };
startTransition(() => {... });:  using startTransition to wrap the state update, which is the navigation in this case. This notifies React that it's okay to postpone processing the state update contained in the callback.
navigate('/Station');: To navigate to the '/Station' route,  invoking the navigate function inside the startTransition callback. This is the action that starts the state update.

 making sure that the navigation action is handled as asynchronously and that any state updates brought about by it won't interfere with synchronous rendering by using startTransition. This can enhance performance, particularly if there are other upgrades taking place at the same time.

**Comment by Witty-Wizard** [comment]
> > @Rohitha-pudu, I am merging this PR, before that can you please explain the bug and how you solved it so that other people can look into it, if they want to learn.
> 
> #43 closes I implemented startTransition to navigate to navigate('/station'),React provides a function called startTransition that lets you tell React that a state update, or a sequence of state updates, can wait.
> 
> ```js
> const Station = () => {
>         // Wrap the state update with startTransition
>         startTransition(() => {
>             navigate('/Station');
>         });
>     };
> startTransition(() => {... });:
> ```
> 
> using startTransition to wrap the state update, which is the navigation in this case. This notifies React that it's okay to postpone processing the state update contained in the callback. `navigate('/Station');`: To navigate to the `'/Station'` route, invoking the navigate function inside the startTransition callback. This is the action that starts the state update.
> 
> making sure that the navigation action is handled as asynchronously and that any state updates brought about by it won't interfere with synchronous rendering by using startTransition. This can enhance performance, particularly if there are other upgrades taking place at the same time.

Great!!, I Will merge the PR

**Comment by Rohitha-pudu** [comment]
> > > @Rohitha-pudu, I am merging this PR, before that can you please explain the bug and how you solved it so that other people can look into it, if they want to learn.
> > 
> > 
> > #43 closes I implemented startTransition to navigate to navigate('/station'),React provides a function called startTransition that lets you tell React that a state update, or a sequence of state updates, can wait.
> > ```js
> > const Station = () => {
> >         // Wrap the state update with startTransition
> >         startTransition(() => {
> >             navigate('/Station');
> >         });
> >     };
> > startTransition(() => {... });:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > using startTransition to wrap the state update, which is the navigation in this case. This notifies React that it's okay to postpone processing the state update contained in the callback. `navigate('/Station');`: To navigate to the `'/Station'` route, invoking the navigate function inside the startTransition callback. This is the action that starts the state update.
> > making sure that the navigation action is handled as asynchronously and that any state updates brought about by it won't interfere with synchronous rendering by using startTransition. This can enhance performance, particularly if there are other upgrades taking place at the same time.
> 
> Great!!, I Will merge the PR

have u assigned me for this? @Witty-Wizard

**Pull request merged**
