### PR TITLE
Adding enhanced readme file

### PR DESCRIPTION
**Pull request by aasthakourav20**
Fixes: #91
- [x] Feature enhancement
Adding updated Readme file 

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

Closes: #91

### CODE REVIEW

**Review by Witty-Wizard — COMMENTED** [review]
Welcome to Our repository.🎊 Thank you so much for taking the time to point this out.

**Comment by aasthakourav20** [comment]
Hey @Witty-Wizard , changes are done , Kindly review

**Comment by aasthakourav20** [comment]
> Hey @Witty-Wizard , changes are done , Kindly review

Hey @Aryaman9999 , Kindly review the changes

**Review by Witty-Wizard — APPROVED** [review]

**Comment by aasthakourav20** [comment]
Hey @Witty-Wizard , Kindly add labels to this PR  like GSSoC'24 & levels like level1 , level2, level3 . 
Otherwise my points will not be counted.

**Comment by aasthakourav20** [comment]
Hey @Witty-Wizard , Kindly add labels to this PR like GSSoC'24 & levels like level1 , level2, level3 .
Otherwise my points will not be counted.

**Comment by Witty-Wizard** [comment]
Hey @aasthakourav20 , I forgot to add the labels, I haved added them now.

**Pull request merged**
