### PR TITLE
Added Dockerfile to the project and steps to use it

### PR DESCRIPTION
**Pull request by abhayymishraa**
## Context
This pull request aims to introduce Dockerization to the project. By containerizing the application, we aim to achieve better consistency across different environments and streamline the deployment process.

## Description
To achieve Dockerization, the following steps will be taken:
- Created a Dockerfile to define the Docker image.
- Copied the package.json file to the Docker image.
- Installed dependencies using npm install.
- Copied the project files into the Docker image.
- Exposed port 5173 for the application.
- Configured the CMD to run the application in development mode using npm run dev.

## Changes in the codebase
The primary changes in the codebase include:
- Added a Dockerfile to define the Docker image.
- Updated the .dockerignore file to exclude unnecessary files from the Docker image.
- Made modifications to the Vite configuration to specify the host.
- Updated the README.md file to include instructions on how to run the application using Docker.

## Changes outside the codebase
No changes outside the codebase are required for this pull request.

## Additional information
- By containerizing the application, we ensure consistency in the development and production environments.
- Dockerizing the application simplifies the deployment process and facilitates scaling.

### Tested conatainerization process
####Screeenshots:
Screenshot from 2024-05-24 02-13-13

Screenshot from 2024-05-24 02-12-17

Followed proper layering in dockerfile 
contribution regarding gssoc

### CODE REVIEW

**Review by Witty-Wizard — COMMENTED** [review]
Welcome to Our repository.🎊 Thank you so much for taking the time to point this out.

**Comment by Witty-Wizard** [comment]
@abhayymishraa,
Please create an issue for it so that we can like the PR and the issue

**Review by Witty-Wizard — CHANGES_REQUESTED** [review]
Hi!, @abhayymishraa 
Great Work!, I have listed the following task please complete them then I will merge your PR

- [ ] **Docker for Gitpod:** Implement Docker configurations for Gitpod, enabling seamless integration with the Gitpod development environment.
- [ ] **Docker for devcontainer:** Create Docker configurations for Visual Studio Code's devcontainer, facilitating consistent development environments for contributors.
- [ ] **Setup GitHub Action for Docker:** Create a GitHub Action workflow to automate Docker-related tasks such as building Docker images, running tests within Docker containers, and deploying Docker containers to specified environments.

**Comment by abhayymishraa** [comment]
did i neeed to make issue? now

**Comment by Witty-Wizard** [comment]
> did i neeed to make issue? now

No I have done it.

**Comment by abhayymishraa** [comment]
sir there's a problem sir you mention those steps actually i'm not  familiar with that stack still i can make it !!! sir i also have an idea to build docker compose to reflect the changes happening to code

**Comment by Witty-Wizard** [comment]
> sir actually what beahaviour you wanted from gitpod?? is it when opening in gitpod it will start container and start running already and the other way like npm run dev to see the chnages ofcourse in this condition no logic for dockerfile is required i can make both

Oh i see, you can skip the gitpod task, and work on the github action task, which will build the container to check if the dockerfile is valid or it has some error.
Also, comment on the issue so that i can assign it to you

**Pull request merged**
